version: '3.8'

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new_york_taxi

    volumes:
      - "postgres-data-volume:/var/lib/postgresql/data"
    restart: always

    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: oludaredolamu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  jupyter:
    image: jupyter/pyspark-notebook
    ports:
      - "8888:8888"
    
volumes:
  postgres-data-volume: