version: '3.8'

services:
  postgresdb:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: new_york_taxi
    volumes:
      - "./yellow_taxi_data:/var/lib/postgresql/data"
    restart: always
    ports:
      - "5432:5432"
    networks:
      - pg-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: oludaredolamu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - "./pgadmin_data:/var/lib/pgadmin"
    networks:
      - pg-network
    depends_on:
      - postgresdb
    
networks:
  pg-network:
    name: pg-network